---
# Handler to handle DB tier notifications

- name: restart mariadb
  #service: name=mysqld state=restarted
  service: name=mariadb state=restarted

- name: restart iptables
  service: name=iptables state=restarted
