---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   #- mysql-server
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python
  environment: "{{proxy_env}}"
#   environment:
#     http_proxy: http://70.10.15.10:8080
#     https_proxy: https://70.10.15.10:8080

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  #- restart mysql
  - restart mariadb

- name: Start Mysql Service
  #service: name=mysqld state=started enabled=yes
  service: name=mariadb state=started enabled=yes

#- name: insert iptables rule
#  #lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#  lineinfile: dest=/usr/sbin/iptables state=present regexp="{{ mysql_port }}"
#              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
